#!/usr/bin/env python3
"""Create private path macros for the pinned Mobi-pi source tree."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


DEFAULT_ROOT = Path("/share/jhk/MobiWAM")


def atomic_create(path: Path, content: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if path.read_text(encoding="utf-8") == content:
            return "unchanged"
        raise RuntimeError(
            f"Refusing to overwrite an existing private macro with different content: {path}"
        )

    temporary = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    temporary.write_text(content, encoding="utf-8")
    os.replace(temporary, path)
    return "created"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    allowed_root = DEFAULT_ROOT.resolve()
    if root != allowed_root:
        raise RuntimeError(f"Project root must be exactly {allowed_root}: {root}")

    repo = root / "Mobipi"
    if not (repo / "mobipi" / "macros.py").is_file():
        raise FileNotFoundError(f"Mobi-pi source tree not found: {repo}")

    directories = {
        "scene_models": root / "data" / "scene_models",
        "checkpoints": root / "checkpoints" / "inherited" / "chensiyu-20260830",
        "logs": root / "artifacts" / "MMWAM-OBC-001" / "runs",
        "data": root / "data" / "inherited" / "chensiyu-20260830",
        "robomimic": root / "artifacts" / "MMWAM-OBC-001" / "robomimic",
    }
    for directory in directories.values():
        directory.mkdir(parents=True, exist_ok=True)

    mobipi_content = f'''"""Machine-local Mobi-pi paths. Generated by configure_mobipi_paths.py."""

SCENE_MODEL_ROOT_DIR = {str(directories["scene_models"])!r}
POLICY_CKPT_ROOT_DIR = {str(directories["checkpoints"])!r}
LOG_ROOT_DIR = {str(directories["logs"])!r}
DATA_ROOT_DIR = {str(directories["data"])!r}
'''

    robocasa_content = f'''"""Machine-local RoboCasa paths. Generated by configure_mobipi_paths.py."""

DATASET_BASE_PATH = {str(directories["data"])!r}
'''

    robomimic_content = f'''"""Machine-local robomimic paths. Generated by configure_mobipi_paths.py."""

WANDB_ENTITY = None
WANDB_API_KEY = None
EXPDATA_BASE_PATH = {str(directories["robomimic"])!r}
'''

    results = {
        repo / "mobipi" / "macros_private.py": mobipi_content,
        repo / "external" / "robocasa" / "robocasa" / "macros_private.py": robocasa_content,
        repo / "external" / "robomimic" / "robomimic" / "macros_private.py": robomimic_content,
    }
    for path, content in results.items():
        status = atomic_create(path, content)
        print(f"{status}: {path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
